name: test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

jobs:
  integration:
    name: Integration tests
    strategy:
      matrix:
        platform: [macos-11]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Show host info
        run: |
          uname -a
          sw_vers
          ifconfig
      - name: Make Install (x86_64)
        run: |
          # compile for x86_64
          sudo make PREFIX=/opt/socket_vmnet install
          if file /opt/socket_vmnet/bin/* | grep -q arm64 ; then false ; fi
      - name: Cleanup
        run: |
          sudo make clean
      - name: Make Install (arm64)
        run: |
          # cross-compile for arm64
          sudo make PREFIX=/opt/socket_vmnet.arm64 ARCH=arm64 install
          if file /opt/socket_vmnet.arm64/bin/* | grep -q x86_64 ; then false ; fi
      - name: Print launchd status (shared mode)
        run: launchctl print system/io.github.lima-vm.socket_vmnet
      - name: Install test dependencies
        run: brew install qemu bash coreutils
      - name: Test (shared mode)
        run: ./test/test.sh /var/run/socket_vmnet
# Bridged mode cannot be tested on GHA
